/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classess.Bill;
import Classess.Storing;
import Database.DBManager;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class GenerateBill extends javax.swing.JFrame {

    /**
     * Creates new form GenerateBill
     */
    public GenerateBill() {
        initComponents();
    }

    DefaultTableModel model;
    
    GenerateBill(Bill bill) {
        initComponents();
        
        DBManager dbManager = new DBManager();
        bill = dbManager.generateInvoice(bill);
        
        txtInvoiceNo.setText(bill.getJobNo());
        txtStarting.setText(bill.getStartingDate());
        txtEndingDate.setText(bill.getEndingDate());
        txtClientNo.setText(bill.getClientNo());
        txtName.setText(bill.getName());
        txtAddress.setText(bill.getAddress());
        txtEmail.setText(bill.getEmail());
        txtTeleNo.setText(bill.getTeleNo());
        txtSubTotal.setText(bill.getSubTotal() + "");
        
        ArrayList<Bill> ItemList = new ArrayList<Bill>();
        
        ItemList = dbManager.generateJobItems(bill);
        
        model = (DefaultTableModel) tableItemList.getModel();
        
        for (int i = 0; i < ItemList.size(); i++) {
            Bill get = ItemList.get(i);
            
            Object itemRow[] = new Object[6];
            itemRow[0] = get.getItemName();
            itemRow[1] = get.getSqftArea();
            itemRow[2] = get.getNoOfItem();
            itemRow[3] = get.getPerSqftRate();
            itemRow[4] = get.getDays();
            itemRow[5] = get.getItemTotal();
            
            model.addRow(itemRow);
        }
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTo = new javax.swing.JLabel();
        lblInvoiceNo = new javax.swing.JLabel();
        txtEndingDate = new javax.swing.JTextField();
        txtStarting = new javax.swing.JTextField();
        lblClientNo = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtClientNo = new javax.swing.JTextField();
        lblTeleNo = new javax.swing.JLabel();
        txtTeleNo = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblStoringPeriod = new javax.swing.JLabel();
        txtInvoiceNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableItemList = new javax.swing.JTable();
        lblSubTotal = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        btnAddAStoring = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1355, 950));
        setMinimumSize(new java.awt.Dimension(1355, 950));
        setPreferredSize(new java.awt.Dimension(1355, 950));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel1.setText("INVOICE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 470, 110));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SmartWarehouse (Pvt) Ltd");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 330, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("No: 73, Ramanayake Mawatha, Colombo 2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 60, -1, -1));

        jLabel4.setText("Tele: 0112-123456    Fax: 0113-001122");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, 230, -1));

        jLabel5.setText("www.smartwarehouse.lk");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/SmartWarehouse.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 150));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTo.setText("to");
        jPanel3.add(lblTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, 20, 30));

        lblInvoiceNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInvoiceNo.setText("Invoice No:");
        jPanel3.add(lblInvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 120, 30));

        txtEndingDate.setEditable(false);
        txtEndingDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEndingDate.setBorder(null);
        txtEndingDate.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtEndingDate.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtEndingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, 120, 30));

        txtStarting.setEditable(false);
        txtStarting.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtStarting.setBorder(null);
        txtStarting.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtStarting.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtStarting, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 110, 30));

        lblClientNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClientNo.setText("Client No:");
        jPanel3.add(lblClientNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 120, 30));

        txtAddress.setEditable(false);
        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAddress.setBorder(null);
        txtAddress.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtAddress.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 530, 30));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setText("Name:");
        jPanel3.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, 30));

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.setBorder(null);
        txtName.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtName.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 530, 30));

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddress.setText("Address:");
        jPanel3.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 120, 30));

        txtClientNo.setEditable(false);
        txtClientNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtClientNo.setBorder(null);
        txtClientNo.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtClientNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 160, 30));

        lblTeleNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTeleNo.setText("Tele No:");
        jPanel3.add(lblTeleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 120, 30));

        txtTeleNo.setEditable(false);
        txtTeleNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTeleNo.setBorder(null);
        txtTeleNo.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtTeleNo.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtTeleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 290, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmail.setText("Email:");
        jPanel3.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, 30));

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtEmail.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 530, 30));

        lblStoringPeriod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStoringPeriod.setText("Storing Period:");
        jPanel3.add(lblStoringPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 140, 30));

        txtInvoiceNo.setEditable(false);
        txtInvoiceNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtInvoiceNo.setBorder(null);
        txtInvoiceNo.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtInvoiceNo.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtInvoiceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceNoActionPerformed(evt);
            }
        });
        jPanel3.add(txtInvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 160, 30));

        tableItemList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Sq.ft Area", "No of Items", "Per Sq.ft Rate", "Duration (Days)", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableItemList.setGridColor(new java.awt.Color(255, 255, 255));
        tableItemList.setRowHeight(20);
        tableItemList.setRowMargin(2);
        tableItemList.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tableItemList.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableItemList.setShowHorizontalLines(false);
        tableItemList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableItemList);
        if (tableItemList.getColumnModel().getColumnCount() > 0) {
            tableItemList.getColumnModel().getColumn(0).setResizable(false);
            tableItemList.getColumnModel().getColumn(1).setResizable(false);
            tableItemList.getColumnModel().getColumn(2).setResizable(false);
            tableItemList.getColumnModel().getColumn(3).setResizable(false);
            tableItemList.getColumnModel().getColumn(4).setResizable(false);
            tableItemList.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 1280, 230));

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubTotal.setText("Sub Total:");
        jPanel3.add(lblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 500, 100, 30));

        txtSubTotal.setEditable(false);
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSubTotal.setBorder(null);
        jPanel3.add(txtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 500, 210, 30));

        btnAddAStoring.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddAStoring.setText("New Soring");
        btnAddAStoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAStoringActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddAStoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 660, 140, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Have a nice day!");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 180, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel8.setText("Thank You!");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 260, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1340, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 890));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAStoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAStoringActionPerformed
        AddStoring addStoring = new AddStoring();
        addStoring.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddAStoringActionPerformed

    private void txtInvoiceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvoiceNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoiceNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAStoring;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblClientNo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblInvoiceNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStoringPeriod;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTeleNo;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTable tableItemList;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtClientNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndingDate;
    private javax.swing.JTextField txtInvoiceNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStarting;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTeleNo;
    // End of variables declaration//GEN-END:variables
}
