/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static Database.DBManager.userName;
import static Database.DBManager.role;
import Classess.User;
import Database.DBManager;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lblHeading1 = new javax.swing.JLabel();
        lblHeading2 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtuName = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelFooter = new javax.swing.JPanel();
        lblFooter1 = new javax.swing.JLabel();
        lblFooter2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(1345, 820));
        setMinimumSize(new java.awt.Dimension(1345, 820));
        setPreferredSize(new java.awt.Dimension(1345, 820));
        setResizable(false);
        setSize(new java.awt.Dimension(1345, 820));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(204, 204, 204));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading1.setText("Storing System");
        panelHeader.add(lblHeading1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        lblHeading2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblHeading2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading2.setText("SmartWarehouse (Pvt) Ltd");
        panelHeader.add(lblHeading2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/SmartWarehouse.png"))); // NOI18N
        panelHeader.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1336, 160));

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setMinimumSize(new java.awt.Dimension(1336, 470));
        panelBody.setPreferredSize(new java.awt.Dimension(1336, 470));
        panelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserName.setText("User Name");
        panelBody.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, 50));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPassword.setText("Password");
        panelBody.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, 50));

        txtuName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtuName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelBody.add(txtuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 450, 50));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelBody.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 450, 50));

        btnLogin.setBackground(new java.awt.Color(51, 204, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelBody.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 210, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        panelBody.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        getContentPane().add(panelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1336, 540));

        panelFooter.setBackground(new java.awt.Color(255, 255, 255));
        panelFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFooter1.setText("Created by Amisha Danansuriya");
        panelFooter.add(lblFooter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, -1, -1));

        lblFooter2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFooter2.setText("All Rights Reserved 2021.");
        panelFooter.add(lblFooter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 50, -1, -1));

        getContentPane().add(panelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1336, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtuName.getText();
        String pass = txtPass.getText();

        User user = new User(username, pass);

        DBManager dbmanager = new DBManager();

        boolean flag = dbmanager.validateUser(user);

        if (flag) {
            JOptionPane.showMessageDialog(null, "Sucessfully Logged in!");

            if (role.equals("Manager")) {
                ManagerMenu managerMenu = new ManagerMenu();
                managerMenu.setVisible(true);
                this.dispose();
            } else if (role.equals("Operator")) {
                OpMenu opMenu = new OpMenu();
                opMenu.setVisible(true);
                this.dispose();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Login Failed", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFooter1;
    private javax.swing.JLabel lblFooter2;
    private javax.swing.JLabel lblHeading1;
    private javax.swing.JLabel lblHeading2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtuName;
    // End of variables declaration//GEN-END:variables
}
