/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author DELL
 */
public class ManagerMenu extends javax.swing.JFrame {

    /**
     * Creates new form ManagerMenu
     */
    public ManagerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblRegClient = new javax.swing.JLabel();
        lblManageClient = new javax.swing.JLabel();
        lblAddStoring = new javax.swing.JLabel();
        lblManageStoring = new javax.swing.JLabel();
        lblCreateUser = new javax.swing.JLabel();
        lblManageUser = new javax.swing.JLabel();
        lblReportsMenu = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Menu");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -30, 140, 60));

        lblRegClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRegClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Create User.png"))); // NOI18N
        lblRegClient.setText("Register Client");
        lblRegClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRegClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblRegClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegClientMouseClicked(evt);
            }
        });
        jPanel4.add(lblRegClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 160, -1));

        lblManageClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManageClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Manage User.png"))); // NOI18N
        lblManageClient.setText("Manage Clients");
        lblManageClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblManageClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblManageClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblManageClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageClientMouseClicked(evt);
            }
        });
        jPanel4.add(lblManageClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 160, -1));

        lblAddStoring.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddStoring.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddStoring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Create Job.png"))); // NOI18N
        lblAddStoring.setText("Add Storing");
        lblAddStoring.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddStoring.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAddStoring.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblAddStoring.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddStoringMouseClicked(evt);
            }
        });
        jPanel4.add(lblAddStoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 160, -1));

        lblManageStoring.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManageStoring.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageStoring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Manage Job.png"))); // NOI18N
        lblManageStoring.setText("Manage Storing");
        lblManageStoring.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblManageStoring.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblManageStoring.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblManageStoring.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageStoringMouseClicked(evt);
            }
        });
        jPanel4.add(lblManageStoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, 160, -1));

        lblCreateUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCreateUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Create User.png"))); // NOI18N
        lblCreateUser.setText("Create User");
        lblCreateUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreateUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCreateUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCreateUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateUserMouseClicked(evt);
            }
        });
        jPanel4.add(lblCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 160, -1));

        lblManageUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManageUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Manage User.png"))); // NOI18N
        lblManageUser.setText("Manage Users");
        lblManageUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblManageUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblManageUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblManageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageUserMouseClicked(evt);
            }
        });
        jPanel4.add(lblManageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 160, -1));

        lblReportsMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblReportsMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Reports.png"))); // NOI18N
        lblReportsMenu.setText("Reports");
        lblReportsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReportsMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblReportsMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblReportsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportsMenuMouseClicked(evt);
            }
        });
        jPanel4.add(lblReportsMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 160, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 1260, 500));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegClientMouseClicked
        RegClient regClient = new RegClient();
        regClient.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegClientMouseClicked

    private void lblManageClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageClientMouseClicked
        ManageClient manageClient = new ManageClient();
        manageClient.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblManageClientMouseClicked

    private void lblAddStoringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddStoringMouseClicked
        AddStoring addStoring = new AddStoring();
        addStoring.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAddStoringMouseClicked

    private void lblManageStoringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageStoringMouseClicked
        ManageStoring manageStoring = new ManageStoring();
        manageStoring.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblManageStoringMouseClicked

    private void lblCreateUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateUserMouseClicked
        CreateUser createUser = new CreateUser();
        createUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCreateUserMouseClicked

    private void lblManageUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageUserMouseClicked
        ManageUsers manageUsers = new ManageUsers();
        manageUsers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblManageUserMouseClicked

    private void lblReportsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMenuMouseClicked
        ReportMenu reportMenu = new ReportMenu();
        reportMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblReportsMenuMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ManagerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblAddStoring;
    private javax.swing.JLabel lblCreateUser;
    private javax.swing.JLabel lblManageClient;
    private javax.swing.JLabel lblManageStoring;
    private javax.swing.JLabel lblManageUser;
    private javax.swing.JLabel lblRegClient;
    private javax.swing.JLabel lblReportsMenu;
    // End of variables declaration//GEN-END:variables
}
