/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static Database.DBManager.userName;
import static Database.DBManager.role;

import Classess.Bill;
import Classess.Storing;
import Database.DBManager;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class ManageStoring extends javax.swing.JFrame {

    /**
     * Creates new form ManageStoring
     */
    Date date;
    SimpleDateFormat dateFormat;    
    
    public ManageStoring() {
        initComponents();
        
        date = new Date();
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        dateClose.setDateFormatString(dateFormat.toLocalizedPattern());
        dateClose.setDate(date);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHEadingClose = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnCloseStoring = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblCloseDate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCComment = new javax.swing.JTextArea();
        lblCComment = new javax.swing.JLabel();
        dateClose = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        txtSearchJobNo = new javax.swing.JTextField();
        lblSearchJobNo = new javax.swing.JLabel();
        btnJobSearch1 = new javax.swing.JButton();
        lblJobNo = new javax.swing.JLabel();
        txtJobNo = new javax.swing.JTextField();
        lblStartingDate = new javax.swing.JLabel();
        txtStartingDate = new javax.swing.JTextField();
        lblEndingDate = new javax.swing.JLabel();
        txtEndingDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1340, 600));
        setMinimumSize(new java.awt.Dimension(1340, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHEadingClose.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHEadingClose.setText("Close Storing");
        jPanel1.add(lblHEadingClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -30, 280, 60));

        btnBack.setBackground(new java.awt.Color(255, 204, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel4.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 250, 140, 40));

        btnCloseStoring.setBackground(new java.awt.Color(51, 204, 255));
        btnCloseStoring.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCloseStoring.setText("Close Storing");
        btnCloseStoring.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCloseStoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseStoringActionPerformed(evt);
            }
        });
        jPanel4.add(btnCloseStoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 140, 40));

        btnReset.setBackground(new java.awt.Color(255, 204, 204));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 140, 40));

        lblCloseDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCloseDate.setForeground(new java.awt.Color(102, 102, 102));
        lblCloseDate.setText("Close Date");
        jPanel4.add(lblCloseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 30));

        txtCComment.setBackground(new java.awt.Color(204, 204, 204));
        txtCComment.setColumns(20);
        txtCComment.setRows(5);
        txtCComment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtCComment);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 1060, 100));

        lblCComment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCComment.setForeground(new java.awt.Color(102, 102, 102));
        lblCComment.setText("Comment");
        jPanel4.add(lblCComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 30));

        dateClose.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.add(dateClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 220, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 1260, 320));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearchJobNo.setBackground(new java.awt.Color(204, 204, 204));
        txtSearchJobNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSearchJobNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchJobNoActionPerformed(evt);
            }
        });
        jPanel2.add(txtSearchJobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 210, 30));

        lblSearchJobNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSearchJobNo.setText("Job No");
        jPanel2.add(lblSearchJobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, 30));

        btnJobSearch1.setBackground(new java.awt.Color(51, 204, 255));
        btnJobSearch1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnJobSearch1.setText("Search");
        btnJobSearch1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnJobSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobSearch1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnJobSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1340, 70));

        lblJobNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblJobNo.setForeground(new java.awt.Color(102, 102, 102));
        lblJobNo.setText("Job No");
        jPanel1.add(lblJobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 30));

        txtJobNo.setEditable(false);
        txtJobNo.setBackground(new java.awt.Color(204, 204, 204));
        txtJobNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtJobNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtJobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 200, 30));

        lblStartingDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStartingDate.setForeground(new java.awt.Color(102, 102, 102));
        lblStartingDate.setText("Starting Date");
        jPanel1.add(lblStartingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 110, 30));

        txtStartingDate.setEditable(false);
        txtStartingDate.setBackground(new java.awt.Color(204, 204, 204));
        txtStartingDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtStartingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartingDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtStartingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 180, 30));

        lblEndingDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEndingDate.setForeground(new java.awt.Color(102, 102, 102));
        lblEndingDate.setText("Ending Date");
        jPanel1.add(lblEndingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 110, 30));

        txtEndingDate.setEditable(false);
        txtEndingDate.setBackground(new java.awt.Color(204, 204, 204));
        txtEndingDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEndingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndingDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtEndingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtJobNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobNoActionPerformed

    private void txtStartingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartingDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartingDateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (role.equals("Manager")) {
                ManagerMenu managerMenu = new ManagerMenu();
                managerMenu.setVisible(true);
                this.dispose();
            } else if (role.equals("Operator")) {
                OpMenu opMenu = new OpMenu();
                opMenu.setVisible(true);
                this.dispose();
            }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCloseStoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseStoringActionPerformed
       
        String jobID = txtSearchJobNo.getText();
        String closeDate = dateFormat.format(dateClose.getDate());
        String comment = txtCComment.getText();
        int  status = 0;
        Bill bill = new Bill(jobID, closeDate, comment, status);
        DBManager dbManager = new DBManager();
        boolean falg =  dbManager.closeJob(bill);
        if (falg) {
            JOptionPane.showMessageDialog(null, "Job has been closed!");
            txtSearchJobNo.setText("");
            txtJobNo.setText("");
            txtStartingDate.setText("");
            txtEndingDate.setText("");
            dateClose.setDate(date);
            txtCComment.setText("");
        } else{
            JOptionPane.showMessageDialog(null, "Job closing has been failed!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCloseStoringActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtSearchJobNo.setText("");
        txtJobNo.setText("");
        txtStartingDate.setText("");
        txtEndingDate.setText("");
        dateClose.setDate(date);
        txtCComment.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtEndingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndingDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndingDateActionPerformed

    private void txtSearchJobNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchJobNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchJobNoActionPerformed

    private void btnJobSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobSearch1ActionPerformed
        String jobNo = txtSearchJobNo.getText();
        Storing storing = new Storing(jobNo);
        DBManager dbManager = new DBManager();
        Storing jobSearch = dbManager.jobSearch(storing);

        if (jobSearch == null) {
            JOptionPane.showMessageDialog(null, "Invalid Client Number of Job has been closed!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {

            txtJobNo.setText(jobSearch.getJobNo());
            txtStartingDate.setText(jobSearch.getStartingDate());
            txtEndingDate.setText(jobSearch.getEndingDate());
    }//GEN-LAST:event_btnJobSearch1ActionPerformed
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStoring().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCloseStoring;
    private javax.swing.JButton btnJobSearch1;
    private javax.swing.JButton btnReset;
    private com.toedter.calendar.JDateChooser dateClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCComment;
    private javax.swing.JLabel lblCloseDate;
    private javax.swing.JLabel lblEndingDate;
    private javax.swing.JLabel lblHEadingClose;
    private javax.swing.JLabel lblJobNo;
    private javax.swing.JLabel lblSearchJobNo;
    private javax.swing.JLabel lblStartingDate;
    private javax.swing.JTextArea txtCComment;
    private javax.swing.JTextField txtEndingDate;
    private javax.swing.JTextField txtJobNo;
    private javax.swing.JTextField txtSearchJobNo;
    private javax.swing.JTextField txtStartingDate;
    // End of variables declaration//GEN-END:variables
}
