/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classess.User;
import Database.DBManager;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class ManageUsers extends javax.swing.JFrame {

    /**
     * Creates new form ManageUsers
     */
    public ManageUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        lblExtNo = new javax.swing.JLabel();
        txtExtNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        txtEmpNo = new javax.swing.JTextField();
        lblEmpNo1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtSearchEmpNo = new javax.swing.JTextField();
        lblSearchEmpNo = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnSClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1336, 768));
        setMinimumSize(new java.awt.Dimension(1336, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Manage User");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -30, 280, 60));

        txtUserName.setBackground(new java.awt.Color(204, 204, 204));
        txtUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 300, 30));

        lblFullName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(102, 102, 102));
        lblFullName.setText("Full Name");
        jPanel4.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 30));

        txtFullName.setBackground(new java.awt.Color(204, 204, 204));
        txtFullName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 1000, 30));

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(102, 102, 102));
        lblUserName.setText("User Name");
        jPanel4.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 30));

        lblExtNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExtNo.setForeground(new java.awt.Color(102, 102, 102));
        lblExtNo.setText("Ext No");
        jPanel4.add(lblExtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 20));

        txtExtNo.setBackground(new java.awt.Color(204, 204, 204));
        txtExtNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(txtExtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 280, 30));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 420, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(102, 102, 102));
        lblEmail.setText("Email");
        jPanel4.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 30));

        btnReset.setBackground(new java.awt.Color(255, 204, 204));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 140, 40));

        btnDelete.setBackground(new java.awt.Color(255, 204, 204));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 140, 40));

        lblRole.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(102, 102, 102));
        lblRole.setText("Role");
        jPanel4.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 80, 30));

        cbRole.setBackground(new java.awt.Color(204, 204, 204));
        cbRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operator", "Manager" }));
        cbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoleActionPerformed(evt);
            }
        });
        jPanel4.add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 180, 30));

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPass.setForeground(new java.awt.Color(102, 102, 102));
        lblPass.setText("Password");
        jPanel4.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, 30));

        txtPass.setBackground(new java.awt.Color(204, 204, 204));
        txtPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel4.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 360, 30));

        txtEmpNo.setEditable(false);
        txtEmpNo.setBackground(new java.awt.Color(204, 204, 204));
        txtEmpNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNoActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, 30));

        lblEmpNo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmpNo1.setForeground(new java.awt.Color(102, 102, 102));
        lblEmpNo1.setText("Emp No");
        jPanel4.add(lblEmpNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, 30));

        btnUpdate.setBackground(new java.awt.Color(51, 204, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 140, 40));

        btnBack1.setBackground(new java.awt.Color(255, 204, 204));
        btnBack1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 420, 140, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 1260, 500));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearchEmpNo.setBackground(new java.awt.Color(204, 204, 204));
        txtSearchEmpNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSearchEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchEmpNoActionPerformed(evt);
            }
        });
        jPanel2.add(txtSearchEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 210, 30));

        lblSearchEmpNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSearchEmpNo.setText("Emp No");
        jPanel2.add(lblSearchEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, 30));

        btnSearch.setBackground(new java.awt.Color(51, 204, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 90, 30));

        btnSClear.setBackground(new java.awt.Color(255, 204, 204));
        btnSClear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSClear.setText("Clear");
        btnSClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnSClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 80, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1340, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       
        txtEmpNo.setText("");
        txtUserName.setText("");
        txtPass.setText("");
        cbRole.setSelectedItem("Operator");
        txtFullName.setText("");
        txtExtNo.setText("");
        txtEmail.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String empNo = txtSearchEmpNo.getText();
        User user = new User(empNo);
        DBManager dbManager = new DBManager();
        User userSearch = dbManager.searchUser(user);
        
        if (userSearch == null) {
             JOptionPane.showMessageDialog(null, "Invalid Employee Number", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            
        txtEmpNo.setText(userSearch.getEmpNo());
        txtUserName.setText(userSearch.getUserName());
        txtPass.setText(userSearch.getPass());
        cbRole.setSelectedItem(userSearch.getRole());
        txtFullName.setText(userSearch.getFullName());
        txtExtNo.setText(userSearch.getExtNo());
        txtEmail.setText(userSearch.getEmial());
        }
        
        
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String empNo = txtSearchEmpNo.getText();
        User user = new User(empNo);
        DBManager dbManager = new DBManager();
        boolean flag = dbManager.deleteUser(user);
        
        if (flag) {
            JOptionPane.showMessageDialog(null, "User has been sucessfully removed!");
            txtEmpNo.setText("");
            txtUserName.setText("");
            txtPass.setText("");
            cbRole.setSelectedItem("Operator");
            txtFullName.setText("");
            txtExtNo.setText("");
            txtEmail.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "User removing has been failed!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchEmpNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchEmpNoActionPerformed

    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoleActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpNoActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String userName = txtUserName.getText();
        String pass = txtPass.getText();
        String role = (String) cbRole.getSelectedItem();
        String empNo = txtEmpNo.getText();
        String fullName = txtFullName.getText();
        String extNo = txtExtNo.getText();
        String email = txtEmail.getText();
        
        User user = new User(userName, pass, role, empNo, fullName, extNo, email);
        DBManager dbmanager = new DBManager();
        boolean flag = dbmanager.updateUser(user);
        
        if (flag) {
            JOptionPane.showMessageDialog(null, "User has been sucessfully updated!");
            txtEmpNo.setText("");
            txtUserName.setText("");
            txtPass.setText("");
            cbRole.setSelectedItem("Operator");
            txtFullName.setText("");
            txtExtNo.setText("");
            txtEmail.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "User updation has been failed!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        ManagerMenu managerMenu = new ManagerMenu();
        managerMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnSClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSClearActionPerformed
        txtSearchEmpNo.setText("");
    }//GEN-LAST:event_btnSClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpNo1;
    private javax.swing.JLabel lblExtNo;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSearchEmpNo;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtExtNo;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtSearchEmpNo;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
