/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


/**
 *
 * @author DELL
 */
public class OpMenu extends javax.swing.JFrame {

    /**
     * Creates new form OpMenu
     */
    public OpMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblRegClient = new javax.swing.JLabel();
        lblManageClient = new javax.swing.JLabel();
        lblAddStoring = new javax.swing.JLabel();
        lblManageStoring = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1336, 768));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHeading.setText("Menu");
        jPanel3.add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -30, 140, 60));

        lblRegClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRegClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Create User.png"))); // NOI18N
        lblRegClient.setText("Register Client");
        lblRegClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRegClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblRegClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegClientMouseClicked(evt);
            }
        });
        jPanel4.add(lblRegClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 160, -1));

        lblManageClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManageClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Manage User.png"))); // NOI18N
        lblManageClient.setText("Manage Client");
        lblManageClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblManageClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblManageClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblManageClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageClientMouseClicked(evt);
            }
        });
        jPanel4.add(lblManageClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 160, -1));

        lblAddStoring.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddStoring.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddStoring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Create Job.png"))); // NOI18N
        lblAddStoring.setText("Add Storing");
        lblAddStoring.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddStoring.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAddStoring.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblAddStoring.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddStoringMouseClicked(evt);
            }
        });
        jPanel4.add(lblAddStoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 160, -1));

        lblManageStoring.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManageStoring.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageStoring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Manage Job.png"))); // NOI18N
        lblManageStoring.setText("Manage Storing");
        lblManageStoring.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblManageStoring.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblManageStoring.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblManageStoring.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageStoringMouseClicked(evt);
            }
        });
        jPanel4.add(lblManageStoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, 160, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 1260, 400));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 650, 160, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegClientMouseClicked
        RegClient regClient = new RegClient();
        regClient.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegClientMouseClicked

    private void lblManageClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageClientMouseClicked
        ManageClient manageClient = new ManageClient();
        manageClient.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblManageClientMouseClicked

    private void lblAddStoringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddStoringMouseClicked
        AddStoring addStoring = new AddStoring();
        addStoring.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAddStoringMouseClicked

    private void lblManageStoringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageStoringMouseClicked
        ManageStoring manageStoring = new ManageStoring();
        manageStoring.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblManageStoringMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OpMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblAddStoring;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblManageClient;
    private javax.swing.JLabel lblManageStoring;
    private javax.swing.JLabel lblRegClient;
    // End of variables declaration//GEN-END:variables
}
