/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static Database.DBManager.userName;
import static Database.DBManager.role;

import Classess.Client;
import Database.DBManager;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class RegClient extends javax.swing.JFrame {

    /**
     * Creates new form RegClient
     */
    public RegClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegClient = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtClientNo = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblClientNo = new javax.swing.JLabel();
        lblTeleNo = new javax.swing.JLabel();
        txtTeleNo = new javax.swing.JTextField();
        lblMobile = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblRemark = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRemark = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1336, 768));
        setMinimumSize(new java.awt.Dimension(1336, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegClient.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblRegClient.setText("Register Client");
        jPanel1.add(lblRegClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -30, 310, 60));

        txtClientNo.setBackground(new java.awt.Color(204, 204, 204));
        txtClientNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtClientNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientNoActionPerformed(evt);
            }
        });
        jPanel4.add(txtClientNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 30));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 102, 102));
        lblName.setText("Name");
        jPanel4.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 30));

        txtName.setBackground(new java.awt.Color(204, 204, 204));
        txtName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 1030, 30));

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(102, 102, 102));
        lblAddress.setText("Address");
        jPanel4.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 30));

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 1030, 30));

        lblClientNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClientNo.setForeground(new java.awt.Color(102, 102, 102));
        lblClientNo.setText("Client No");
        jPanel4.add(lblClientNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 30));

        lblTeleNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTeleNo.setForeground(new java.awt.Color(102, 102, 102));
        lblTeleNo.setText("Tele No");
        jPanel4.add(lblTeleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 20));

        txtTeleNo.setBackground(new java.awt.Color(204, 204, 204));
        txtTeleNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(txtTeleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 320, 30));

        lblMobile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMobile.setForeground(new java.awt.Color(102, 102, 102));
        lblMobile.setText("Mobile");
        jPanel4.add(lblMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, 20));

        txtMobile.setBackground(new java.awt.Color(204, 204, 204));
        txtMobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 310, 30));

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("*Permanant address or Company address");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 20));

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("*If corporate client, Register using company name");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        lblRemark.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRemark.setForeground(new java.awt.Color(102, 102, 102));
        lblRemark.setText("Remarks");
        jPanel4.add(lblRemark, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, 30));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 420, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(102, 102, 102));
        lblEmail.setText("Email");
        jPanel4.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 30));

        txtRemark.setBackground(new java.awt.Color(204, 204, 204));
        txtRemark.setColumns(20);
        txtRemark.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtRemark.setLineWrap(true);
        txtRemark.setRows(5);
        txtRemark.setWrapStyleWord(true);
        txtRemark.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(txtRemark);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 1040, -1));

        btnBack.setBackground(new java.awt.Color(255, 204, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel4.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 510, 140, 40));

        btnSubmit.setBackground(new java.awt.Color(51, 204, 255));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel4.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 140, 40));

        btnReset.setBackground(new java.awt.Color(255, 204, 204));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 510, 140, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 1260, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClientNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientNoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (role.equals("Manager")) {
                ManagerMenu managerMenu = new ManagerMenu();
                managerMenu.setVisible(true);
                this.dispose();
            } else if (role.equals("Operator")) {
                OpMenu opMenu = new OpMenu();
                opMenu.setVisible(true);
                this.dispose();
            }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String clientNo = txtClientNo.getText();
        String name = txtName.getText();
        String address = txtAddress.getText();
        String teleNo = txtTeleNo.getText();
        String mobile = txtMobile.getText();
        String email = txtEmail.getText();
        String remark = txtRemark.getText();
        
        Client client = new Client(clientNo, name, address, teleNo, mobile, email, remark);
        DBManager dbmanager = new DBManager();
        boolean flag = dbmanager.regClient(client);
        
        if (flag) {
            JOptionPane.showMessageDialog(null, "Client has been sucessfully created!");
            txtClientNo.setText("");
            txtName.setText("");
            txtAddress.setText("");
            txtTeleNo.setText("");
            txtMobile.setText("");
            txtEmail.setText("");
            txtRemark.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Client creation has been failed!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblClientNo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRegClient;
    private javax.swing.JLabel lblRemark;
    private javax.swing.JLabel lblTeleNo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtClientNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtRemark;
    private javax.swing.JTextField txtTeleNo;
    // End of variables declaration//GEN-END:variables
}
